import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, CalendarDays, CreditCard, HeartHandshake, LockKeyhole, Shirt, BedDouble, Utensils, MapPin, Clock3, House } from 'lucide-react';
import {CTA,Eyebrow,CheckList} from '@/components/ui';
import {getConfig} from '@/lib/config';
import {money} from '@/lib/pricing';
import {areas} from '@/lib/content';
import {businessContact} from '@/lib/business-contact';
export const dynamic='force-dynamic';
export default async function Home(){const config=await getConfig();const min=config.tiers[0];return <>
  <section className="hero"><div className="hero-copy"><Eyebrow>Homekeeping, the Carolina way</Eyebrow><h1>Your home,<br/><em>handled.</em></h1><p className="hero-lead">A clean home. A lighter day.<br/>More time for what matters.</p><p className="hero-description">Professional homekeeping without the phone calls, estimates or waiting.</p><CTA/><Link className="text-link" href="/commercial">Commercial cleaning <ArrowRight size={17}/></Link><div className="hero-note"><Clock3 size={16}/> See your price. Pick your time. Come home clean.</div></div><div className="hero-image"><Image src="/coastal-home.webp" alt="A bright coastal living room with a linen sofa, oak furniture and soft afternoon light" fill priority sizes="(max-width: 760px) 100vw, 55vw"/><div className="image-caption"><span>A little less to do.</span><strong>A little more time to be.</strong></div></div></section>
  <section className="process-strip"><div className="container"><div className="process-heading"><Eyebrow>Beautifully simple</Eyebrow><h2>From to-do.<br/>To done.</h2></div>{[['Tell us about your home.','A few details. An upfront price.'],['Pick your cleaning and time.','The right clean, on your schedule.'],['Book and pay online.','One less thing on your list.']].map(([t,d])=><div className="process-step" key={t}><h3>{t}</h3><p>{d}</p></div>)}</div></section>
  <section className="section container"><div className="section-heading"><div><Eyebrow>A fresh start, your way</Eyebrow><h2>There’s a clean<br/>for every kind of day.</h2></div><p>Routine refresh or a proper reset.<br/>Choose what your home needs.</p></div><div className="service-grid">{[{id:'standard',title:'The everyday reset.',name:'Standard clean',price:min.standard,body:'For normally maintained homes that deserve a little more breathing room.',items:['Kitchens & bathrooms','Dusting, vacuuming & mopping','Bed making & general straightening']},{id:'deep',title:'A little extra care.',name:'Deep clean',price:min.deep,body:'More time for the details. Ideal when your home needs a thorough refresh.',items:['Everything in Standard','Baseboards, doors & cabinet fronts','Extra kitchen & bathroom detail']},{id:'move',title:'Ready for what’s next.',name:'Move-in / move-out',price:min.move,body:'An empty-home clean for a new beginning or a thoughtful goodbye.',items:['A deep-clean foundation','Empty cabinets, drawers & closets','Detail for an empty home']}].map(s=><article className={'service-card '+s.id} key={s.id}><div className="card-top"><span className="eyebrow">{s.name}</span></div><h3>{s.title}</h3><p>{s.body}</p><CheckList items={s.items}/><div className="card-bottom"><span>From <strong>{money(s.price)}</strong></span><Link href={'/book?service='+s.id} aria-label={'Get my instant price for '+s.name}><ArrowRight size={22}/></Link></div></article>)}</div><div className="section-footnote">Starting prices for homes up to 999 sq ft. Your home size and selections determine your price. <Link href="/services">See everything included <ArrowRight size={15}/></Link></div></section>
  <section className="homekeeping-band"><div className="container split"><div><Eyebrow>More than a clean house</Eyebrow><h2>Make my life<br/><em>easier.</em></h2><p>The laundry basket. The dishes. The bed that needs fresh sheets. Add a little help with the things that keep ending up on your list.</p><CTA/></div><div className="extra-list">{[{id:'dishes',title:'Dishes, handled.',description:'Come home to one less chore.',Icon:Utensils},{id:'laundry',title:'Laundry, handled.',description:'Washed, dried and folded.',Icon:Shirt},{id:'linens',title:'Fresh sheets, handled.',description:'That just-changed-bed feeling.',Icon:BedDouble}].map(({id,title,description,Icon})=><div key={id}><Icon size={25} strokeWidth={1.4} aria-hidden="true"/><div><h3>{title}</h3><p>{description}</p></div><span>from {money(config.addons.find(a=>a.id===id)?.price||0)}</span></div>)}<p className="small-text">Choose your extras when you book. Any applicable tax is shown before payment.</p></div></div></section>
  <section className="section container recurring-section"><div><Eyebrow>Love coming home to this?</Eyebrow><h2>Keep it that way.</h2><p>Build a little ease into your routine.<br/>Recurring savings apply to your base cleaning.</p></div><div className="frequency-cards">{[['weekly','Every week'],['two_weeks','Every 2 weeks'],['four_weeks','Every 4 weeks']].map(([f,label])=><Link href={'/book?frequency='+f} key={f}><CalendarDays size={23} strokeWidth={1.3}/><h3>{label}</h3><strong>Save {config.discounts[f as keyof typeof config.discounts]}%</strong></Link>)}</div><p className="small-text">Your same weekday. Your same time. Automatically reserved and billed at your chosen frequency. Manage or cancel your subscription online.</p></section>
  <section className="promise-section"><div className="container split"><div><Eyebrow>Care you can feel good about</Eyebrow><h2>Your home is personal.<br/>We treat it that way.</h2><p>If we miss something included in your booked clean, let us know within 24 hours. We’ll arrange a return visit to correct that area at no additional charge.</p><Link href="/policies/service" className="text-link">Our service promise <ArrowRight size={17}/></Link></div><div className="trust-grid">{[[CreditCard,'A clear price','Your complete total, before you pay.'],[LockKeyhole,'Privacy matters','Access details stay with the people who need them.'],[HeartHandshake,'Thoughtful care','Clear scope, useful instructions and follow-through.'],[House,'Made for your home','The right cleaning, with the extras you choose.']].map(([Icon,title,body])=>{const I=Icon as typeof House;return <div key={String(title)}><I size={24} strokeWidth={1.4}/><h3>{String(title)}</h3><p>{String(body)}</p></div>})}</div></div></section>
  <section className="section container area-section"><MapPin size={28} strokeWidth={1.4}/><Eyebrow>Proudly starting close to home</Eyebrow><h2>A little more ease<br/>in Eastern North Carolina.</h2><p>Launching in New Bern and neighboring Craven County communities.<br/>Enter your ZIP to check your address.</p><div className="area-links">{areas.map(a=><Link key={a.slug} href={'/service-areas/'+a.slug}>{a.name}<ArrowUp/></Link>)}</div><CTA/></section>
  <section className="final-cta"><div className="container"><Eyebrow>Your weekend is calling</Eyebrow><h2>Leave the cleaning to us.</h2><CTA light/></div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'LocalBusiness',name:'Carolina Homekeeping Co.',telephone:businessContact.phoneE164,url:process.env.APP_URL||'https://carolinahomekeeping.com',description:'Residential and commercial cleaning and homekeeping in the New Bern area.',areaServed:areas.map(a=>({'@type':'City',name:a.name+', North Carolina'})),parentOrganization:{'@type':'Organization',name:'Send A Scout LLC'}}).replace(/</g,'\\u003c')}}/>
</>;}
function ArrowUp(){return <ArrowRight size={16}/>;}
