import Link from 'next/link';
import {CheckCircle2,CalendarPlus} from 'lucide-react';
import {money,serviceNames,frequencyNames,type PricingConfig,type Service,type Frequency} from '@/lib/pricing';
import {slotDate,slotTime} from '@/lib/appointment-display';
import {bookingCalendar} from '@/lib/booking-calendar';
export type ConfirmedBooking={reference:string;service:Service;amount:number;slot:{starts_at:string};frequency:Frequency;manageUrl?:string|null;address?:string;addons?:{name:string;quantity:number}[];emailStatus?:string};
export function BookingSuccess({booking,discounts}:{booking:ConfirmedBooking;discounts:PricingConfig['discounts']}){
  const calendar=bookingCalendar({reference:booking.reference,service:booking.service,startsAt:booking.slot.starts_at,address:booking.address});
  return <div className="success-panel booking-success"><CheckCircle2 size={46} aria-hidden="true"/><p className="eyebrow">One less thing on your list</p><h1>Your home is handled.</h1><p>Your cleaning is confirmed. We’ll take it from here.</p>
    <div className="confirmation-details"><p className="eyebrow">Booking {booking.reference}</p><h2>{serviceNames[booking.service]}</h2><p className="confirmation-date">{slotDate(booking.slot.starts_at)}<br/><strong>{slotTime(booking.slot.starts_at)} start · Eastern</strong></p>{booking.address&&<p>{booking.address}</p>}<p>{frequencyNames[booking.frequency]}</p>{!!booking.addons?.length&&<p className="small-text">{booking.addons.map(a=>`${a.quantity} × ${a.name}`).join(' · ')}</p>}<p><strong>Paid {money(booking.amount)}</strong></p><p className="small-text">{booking.emailStatus==='sent'?'Your confirmation email has been sent.':'Your confirmation email is queued. Save your booking reference above.'}</p></div>
    <div className="confirmation-actions"><a className="button" download={`Carolina-Homekeeping-${booking.reference}.ics`} href={'data:text/calendar;charset=utf-8,'+encodeURIComponent(calendar)}><CalendarPlus size={18} aria-hidden="true"/>Add to my calendar</a>{booking.manageUrl?<Link className="button outline" href={booking.manageUrl}>Manage my subscription</Link>:<Link className="text-link" href="/contact">Need to change something?</Link>}</div><p className="small-text">The calendar file saves this appointment’s start time. Please secure pets and make sure we can access your home.</p>
    {booking.frequency==='once'?<section className="confirmation-recurring" aria-labelledby="recurring-success-title"><p className="eyebrow">Love coming home to this?</p><h2 id="recurring-success-title">Keep it that way.</h2><p>Make a clean home part of your routine. Save on the base cleaning for future visits.</p><div className="confirmation-routines">{(['weekly','two_weeks','four_weeks'] as const).map(f=><Link key={f} href={`/book?service=standard&frequency=${f}`}><span>{frequencyNames[f]}</span><strong>Save {discounts[f]}%</strong><span>Plan future visits →</span></Link>)}</div><p className="small-text">Your confirmed appointment stays as booked. Choose a date after this visit for your new recurring plan. You’ll review its price, schedule and automatic billing before paying.</p></section>:<p className="confirmation-plan">Your recurring weekday and start time are reserved automatically. Use your private subscription link to manage payments or cancel future renewals.</p>}
  </div>;
}
