'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,Check,ChevronDown,Minus,Plus,LockKeyhole,CalendarDays} from 'lucide-react';
import {calculateQuote,money,services,frequencies,serviceNames,frequencyNames,type PricingConfig,type QuoteInput,type Service,type Frequency,type Quote} from '@/lib/pricing';
import {ContactForm} from './contact-form';
import {AppointmentPicker} from './appointment-picker';
import {estimateMinutes,durationLabel,type SchedulingConfig,type AppointmentOption} from '@/lib/scheduling';
type Slot=AppointmentOption;
export const slotDate=(date:string)=>new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',month:'short',day:'numeric'}).format(new Date(date));
export const slotTime=(date:string)=>new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'numeric',minute:'2-digit'}).format(new Date(date));
const titles=['Where’s home?','A little about your home.','Your home. Your kind of clean.','Make my life easier.','Keep that clean-home feeling.','A time that works for you.','The final little details.','Your home is almost handled.'];
const descriptions=['Let’s check your address in our launch area.','A few quick details are all we need to show your price.','Choose the level of care your home needs.','A little extra help goes a long way. Everything here is optional.','Choose a routine, or start with just one clean.','Choose a start time. We reserve the full estimated cleaning time. All times are Eastern.','Tell us where to send your confirmation and how to access your home.','Review everything, then pay securely with Stripe.'];
export function BookingFlow({config,scheduling,initial,leadReady}:{config:PricingConfig;scheduling:SchedulingConfig;initial:Record<string,string|undefined>;leadReady:boolean}){
 const [step,setStep]=useState(0);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [slots,setSlots]=useState<Slot[]>([]);const [loadingSlots,setLoadingSlots]=useState(false);const [availabilityOpen,setAvailabilityOpen]=useState(true);
 const [input,setInput]=useState<QuoteInput>({zip:'',sqft:1500,bedrooms:3,bathrooms:2,pets:'none',condition:'maintained',emptyHome:false,service:services.includes(initial.service as Service)?initial.service as Service:'standard',frequency:frequencies.includes(initial.frequency as Frequency)?initial.frequency as Frequency:'once',addons:{}});
 const [home,setHome]=useState({address:'',city:'New Bern',state:'NC' as const,access:'',instructions:''});
 const [contact,setContact]=useState({name:'',email:'',phone:''});const [slotId,setSlotId]=useState('');const [accepted,setAccepted]=useState(false);const [leadSaved,setLeadSaved]=useState(false);
 const stepRef=useRef<HTMLDivElement>(null);
 let quote:Quote|null=null;try{quote=calculateQuote({...input,zip:input.zip||config.zips[0]},config);}catch{quote=null;}
 const unsupported=input.zip.length===5&&!config.zips.includes(input.zip);
 const needsReview=input.sqft>=3500||input.condition==='excessive';
 const selectedSlot=slots.find(s=>s.id===slotId);
 const durationMinutes=estimateMinutes(input,scheduling);
 const update=<K extends keyof QuoteInput>(key:K,value:QuoteInput[K])=>setInput(i=>({...i,[key]:value}));
 const changeStep=(n:number)=>{setError('');setStep(n);stepRef.current?.scrollIntoView({behavior:'smooth',block:'start'});};
 useEffect(()=>{setSlotId('');setAccepted(false);},[input]);
 useEffect(()=>{
  if(step!==5)return;
  let active=true;const controller=new AbortController();setLoadingSlots(true);setSlots([]);
  fetch('/api/availability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input),signal:controller.signal}).then(async r=>{
   const d=await r.json();if(!r.ok)throw new Error(d.error);
   if(active){setSlots(d.slots);setSlotId(current=>d.slots.some((s:Slot)=>s.id===current)?current:'');setAvailabilityOpen(d.open);if(d.durationMinutes&&d.durationMinutes!==durationMinutes){setSlots([]);setSlotId('');setError('Our time estimates have changed. Please reload to review your cleaning before scheduling.');}}
  }).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoadingSlots(false)});
  return()=>{active=false;controller.abort()};
 },[step,input,durationMinutes]);
 useEffect(()=>{if(!leadSaved)return;const timer=setTimeout(()=>{fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'residential',contact,address:`${home.address}, ${home.city}, NC ${input.zip}`,stage:step===7?'payment':'details',quote:input})}).catch(()=>{});},500);return()=>clearTimeout(timer);},[step,input,contact,home.address,home.city,leadSaved]);
 async function next(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');
  if(step===0&&unsupported)return;
  if(step===1&&needsReview)return;
  if(step===2&&quote?.review){setError(quote.reason||'Please review your service.');return;}
  if(step===5&&!slotId){setError('Please choose an available start time.');return;}
  if(step===6){setBusy(true);try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'residential',contact,address:`${home.address}, ${home.city}, NC ${input.zip}`,stage:'payment',quote:input})});const d=await r.json();if(!r.ok)throw new Error(d.error);setLeadSaved(true);}catch(e){setError(e instanceof Error?e.message:'Please try again.');setBusy(false);return;}setBusy(false);}
  if(step===7){if(!accepted)return;setBusy(true);try{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,contact,home,scheduledStart:slotId,expectedDuration:durationMinutes,policyAccepted:true,policyVersion:'2026-09-19',photoConsent:false,expectedTotal:quote?.total})});const d=await r.json();if(!r.ok)throw new Error(d.error);window.location.assign(d.url);}catch(e){setError(e instanceof Error?e.message:'Payment could not start. Please try again.');setBusy(false);}return;}
  changeStep(step+1);
 }
 const reviewForm=(reason:string)=><div className="notice"><h3>Let’s give your home a personal plan.</h3><p>{reason}</p><ContactForm type="residential" compact quote={input} address={`${home.address}, ${home.city}, NC ${input.zip}`} leadReady={leadReady} stage="review"/></div>;
 return <div className="booking-page"><div className="container"><div className="booking-top"><Link href="/"><ArrowLeft size={16}/> Back to home</Link><span>Clear pricing. Thoughtful homekeeping.</span></div><div className="booking-layout"><div className="booking-content" ref={stepRef}><div className="step-progress" aria-label={`Step ${step+1} of 8`}>{titles.map((_,i)=><span key={i} className={i<=step?'done':''}/>)}</div><p className="eyebrow">Step {step+1} of 8 · {['Location','Your home','Your clean','The extras','Your routine','Your time','Your details','Review & pay'][step]}</p><h1>{titles[step]}</h1><p className="step-description">{descriptions[step]}</p>
 <form onSubmit={next}>
 {step===0&&<><label className="field"><span>Service address</span><input required autoComplete="street-address" value={home.address} onChange={e=>setHome({...home,address:e.target.value})} placeholder="Street address and unit, if any" minLength={5} maxLength={250}/></label><div className="field-row"><label className="field"><span>City</span><input required value={home.city} autoComplete="address-level2" onChange={e=>setHome({...home,city:e.target.value})}/></label><label className="field"><span>ZIP code</span><input required inputMode="numeric" autoComplete="postal-code" pattern="[0-9]{5}" maxLength={5} value={input.zip} onChange={e=>update('zip',e.target.value.replace(/\D/g,''))} placeholder="28562"/></label></div><p className="small-text">Currently serving select addresses in the New Bern area, North Carolina.</p>{unsupported&&<div className="notice">We’re not serving this ZIP yet. You can leave your details below so we can check your location.</div>}</>}
 {step===1&&<><label className="field"><span>Approximate square footage</span><select value={input.sqft} onChange={e=>update('sqft',Number(e.target.value))}>{config.tiers.map((t,i)=><option key={t.maxSqft} value={i===0?999:config.tiers[i-1].maxSqft+1}>{t.label}</option>)}<option value={3500}>3,500 sq ft or more</option></select></label><div className="field-row"><label className="field"><span>Bedrooms</span><select value={input.bedrooms} onChange={e=>update('bedrooms',Number(e.target.value))}>{Array.from({length:11},(_,i)=><option key={i} value={i}>{i===0?'Studio':i}</option>)}</select></label><label className="field"><span>Bathrooms</span><select value={input.bathrooms} onChange={e=>update('bathrooms',Number(e.target.value))}>{Array.from({length:16},(_,i)=><option key={i} value={(i+1)/2}>{(i+1)/2}</option>)}</select></label></div><label className="field"><span>Any pets?</span><select value={input.pets} onChange={e=>update('pets',e.target.value as QuoteInput['pets'])}><option value="none">No pets</option><option value="dog">Dog(s)</option><option value="cat">Cat(s)</option><option value="multiple">Dogs & cats</option><option value="other">Other pets</option></select></label><label className="field"><span>How’s your home looking?</span><select value={input.condition} onChange={e=>{update('condition',e.target.value as QuoteInput['condition']);if(e.target.value==='buildup'&&input.service==='standard')update('service','deep');}}><option value="maintained">Normally maintained — ready for a refresh</option><option value="buildup">Some built-up grime — needs a deep clean</option><option value="excessive">Heavy clutter, damage or unusual conditions</option></select></label><label className="check-field"><input type="checkbox" checked={input.emptyHome} onChange={e=>update('emptyHome',e.target.checked)}/><span>The home will be empty of furniture and belongings.</span></label></>}
 {step===2&&<div className="choice-stack">{services.map(s=>{let q;try{q=calculateQuote({...input,service:s,frequency:s==='move'?'once':input.frequency,addons:{}},config)}catch{q=null}return <button type="button" key={s} aria-pressed={input.service===s} className={'choice '+(input.service===s?'selected':'')} onClick={()=>setInput(i=>({...i,service:s,frequency:s==='move'?'once':i.frequency,addons:s==='move'?Object.fromEntries(Object.entries(i.addons).filter(([k])=>k!=='cabinets')):i.addons}))}><span className="choice-radio">{input.service===s&&<Check size={13}/>}</span><span className="choice-body"><h2>{serviceNames[s]}</h2><p>{s==='standard'?'Kitchens, bathrooms, dusting, floors and everyday straightening.':s==='deep'?'Standard plus baseboards, doors, cabinet fronts and extra detail.':'Deep cleaning plus empty cabinets, drawers and closets.'}</p>{q?.review&&<p>{q.reason}</p>}</span><span className="choice-price">{q&&!q.review?money(q.base+q.roomAdjustment):'—'}</span></button>})}<Link className="text-link" href="/services" target="_blank">See what’s included</Link></div>}
 {step===3&&<div>{config.addons.filter(a=>a.enabled&&!(input.service==='move'&&a.id==='cabinets')).map(a=>{const qty=input.addons[a.id]||0;const price=a.id==='pet_hair'?a.price+Math.floor(input.sqft/1500)*1000:a.price;return <div className="addon-row" key={a.id}><div><h3>{a.name}</h3><p>{a.description}</p><div className="addon-price">{money(price)} / {a.unit}{a.taxable?' + tax':''}</div></div><div className="quantity-control"><button type="button" aria-label={`Remove ${a.name}`} disabled={qty===0} onClick={()=>update('addons',{...input.addons,[a.id]:qty-1})}><Minus size={14}/></button><span aria-live="polite">{qty}</span><button type="button" aria-label={`Add ${a.name}`} disabled={qty>=a.max} onClick={()=>update('addons',{...input.addons,[a.id]:qty+1})}><Plus size={14}/></button></div></div>})}</div>}
 {step===4&&<><div className="choice-stack">{frequencies.filter(f=>input.service!=='move'||f==='once').map(f=>{const q=calculateQuote({...input,frequency:f},config);return <button type="button" key={f} aria-pressed={input.frequency===f} className={'choice '+(input.frequency===f?'selected':'')} onClick={()=>update('frequency',f)}><span className="choice-radio">{input.frequency===f&&<Check size={13}/>}</span><span className="choice-body"><h2>{frequencyNames[f]}</h2><p>{f==='once'?'A fresh start, whenever you need it.':`${config.discounts[f]}% off your base cleaning.`}</p></span><span className="choice-price">{money(q.total)}<small>this appointment</small></span></button>})}</div><div className="notice">You’re paying for one appointment today. For recurring service, we’ll coordinate future dates with you. No automatic subscription charges. Discounts apply to the base cleaning and room adjustments; add-ons are priced separately.</div></>}
 {step===5&&<><div className="notice" style={{marginBottom:20}}><strong>Estimated cleaning time: {durationLabel(durationMinutes)}</strong><p>Monday–Friday, 8 AM–5 PM · Saturday, 8 AM–2 PM · Closed Sunday. Cleanings can finish up to one hour after closing: 6 PM on weekdays or 3 PM on Saturdays.</p></div>{loadingSlots?<p className="loading">Checking available cleaning times…</p>:slots.length?<><AppointmentPicker slots={slots} value={slotId} onChange={setSlotId}/><p className="small-text" style={{marginTop:18}}>The start and estimated finish are shown together. Your full time block is reserved when secure checkout begins.</p></>:<div className="notice"><CalendarDays size={26}/><h3 style={{marginTop:12}}>{availabilityOpen?'No times fit this cleaning right now.':'Online booking opens soon.'}</h3><p>{durationMinutes>600?'This selection needs more time than our regular working day. Send us your details for a personal scheduling plan.':'Keep your price and send us your details. We’ll contact you about scheduling.'} This does not reserve an appointment or charge your card.</p></div>}</>}
 {step===6&&<><label className="field"><span>Your name</span><input required minLength={2} maxLength={120} autoComplete="name" value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})}/></label><div className="field-row"><label className="field"><span>Email</span><input required type="email" autoComplete="email" value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/></label><label className="field"><span>Mobile number</span><input required type="tel" minLength={10} maxLength={25} autoComplete="tel" value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/></label></div><label className="field"><span>How will we get in?</span><textarea maxLength={2000} value={home.access} onChange={e=>setHome({...home,access:e.target.value})} placeholder="For example: I’ll be home, or call on arrival. Share entry codes privately when needed."/></label><label className="field"><span>Anything we should know? <small>Optional</small></span><textarea maxLength={2000} value={home.instructions} onChange={e=>setHome({...home,instructions:e.target.value})} placeholder="Pets, delicate surfaces, products, rooms to skip or special requests."/></label><p className="small-text">By continuing, you’re asking us to save this booking and contact you about your cleaning, even if you don’t finish payment. See our <Link href="/policies/privacy" className="row-link" target="_blank">Privacy Policy</Link>.</p></>}
 {step===7&&<><div className="order-section"><h3>Your home</h3><p>{home.address}, {home.city}, NC {input.zip}</p><p>{config.tiers.find(t=>input.sqft<=t.maxSqft)?.label} · {input.bedrooms} bed · {input.bathrooms} bath</p><button type="button" onClick={()=>changeStep(0)}>Edit home</button></div><div className="order-section"><h3>Your cleaning</h3><p>{serviceNames[input.service]} · {frequencyNames[input.frequency]}</p>{quote?.addons.map(a=><p key={a.id}>{a.quantity} × {a.name}</p>)}<button type="button" onClick={()=>changeStep(2)}>Edit cleaning</button></div><div className="order-section"><h3>Your scheduled cleaning</h3><p>{selectedSlot?`${slotDate(selectedSlot.starts_at)}, ${slotTime(selectedSlot.starts_at)}–${slotTime(selectedSlot.ends_at)} Eastern`:'Please reselect your appointment.'}</p><p>Estimated time: {durationLabel(durationMinutes)}. Finish time is an estimate.</p><button type="button" onClick={()=>changeStep(5)}>Edit time</button></div><div className="order-section"><h3>Confirmation goes to</h3><p>{contact.name} · {contact.email}</p><p>{contact.phone}</p><button type="button" onClick={()=>changeStep(6)}>Edit details</button></div><div className="policy-summary"><strong>Clear expectations, before you pay.</strong><ul><li>More than 48 hours: free cancellation or rescheduling.</li><li>24–48 hours: 25% cancellation fee, or reschedule with a credit.</li><li>Less than 24 hours: 50% cancellation charge.</li><li>No access after reasonable contact attempts: up to 100%.</li></ul><p>Something included was missed? Contact us within 24 hours and we’ll arrange a return to correct that area.</p><p>Cleaning excludes hazardous materials, mold, pests, heavy clutter, construction debris, high ladder work and restoration. Unexpected conditions are discussed before additional work or charges.</p></div><label className="check-field"><input required type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I agree to the <Link href="/policies/terms" target="_blank">Terms</Link>, <Link href="/policies/cancellation" target="_blank">Cancellation Policy</Link>, and <Link href="/policies/service" target="_blank">Service & Satisfaction Policy</Link>, and have read the <Link href="/policies/privacy" target="_blank">Privacy Policy</Link>.</span></label><p className="small-text"><LockKeyhole size={14}/> Card details stay with Stripe. Apple Pay and Google Pay appear when supported by your device and Stripe.</p></>}
 {error&&<p className="error-message" role="alert">{error}</p>}
 <div className="booking-actions">{step>0&&<button type="button" className="back-button" onClick={()=>changeStep(step-1)} disabled={busy}><ArrowLeft size={16}/> Back</button>}{!((step===0&&unsupported)||(step===1&&needsReview)||(step===5&&!slots.length))&&<button className="button" type="submit" disabled={busy||loadingSlots||(step===7&&!accepted)}>{busy?'Just a moment…':step===7?`Pay ${money(quote?.total||0)} securely`:step===3?'Continue':step===0?'See my price':'Continue'}<ArrowRight size={17}/></button>}</div>
 </form>
 {step===0&&unsupported&&<ContactForm type="residential" compact quote={input} address={`${home.address}, ${home.city}, NC ${input.zip}`} stage="outside_area" leadReady={leadReady}/>}
 {step===1&&needsReview&&reviewForm(input.sqft>=3500?'Homes of 3,500 sq ft or more need a personal plan.':'Unusual conditions need a review before we can commit to a cleaning.')}
 {step===5&&!loadingSlots&&!slots.length&&<ContactForm type="residential" compact quote={input} address={`${home.address}, ${home.city}, NC ${input.zip}`} stage="awaiting_availability" leadReady={leadReady}/>}
 </div><aside className="booking-summary" id="price-summary"><p className="eyebrow">Your home, handled.</p><h2>Your cleaning</h2>{step<1?<p className="summary-empty">A few details about your home, then a clear price. No calls or estimates to wait for.</p>:quote&&!quote.review?<><div className="summary-row"><span>{serviceNames[input.service]}</span><span>{money(quote.base)}</span></div><p className="small-text" style={{marginTop:-8,marginBottom:18}}>{config.tiers.find(t=>input.sqft<=t.maxSqft)?.label}</p>{quote.roomAdjustment>0&&<div className="summary-row"><span>Room adjustments</span><span>{money(quote.roomAdjustment)}</span></div>}{quote.addons.map(a=><div className="summary-row" key={a.id}><span>{a.quantity} × {a.name}</span><span>{money(a.amount)}</span></div>)}{quote.discount>0&&<div className="summary-row discount"><span>Recurring savings ({quote.discountPercent}%)</span><span>−{money(quote.discount)}</span></div>}{quote.tax>0&&<div className="summary-row"><span>Tax on selected extras</span><span>{money(quote.tax)}</span></div>}<div className="summary-row"><span>Estimated cleaning time</span><span>{durationLabel(durationMinutes)}</span></div><div className="summary-total"><span>Total for this visit</span><strong aria-live="polite">{money(quote.total)}</strong></div>{selectedSlot&&<p className="small-text" style={{marginTop:16}}>{slotDate(selectedSlot.starts_at)}<br/>{slotTime(selectedSlot.starts_at)}–{slotTime(selectedSlot.ends_at)} Eastern</p>}</>:<p className="summary-empty">{quote?.reason||'Please review your selections.'}</p>}<p className="summary-note">No hidden mandatory fees.<br/>Your full price is shown before payment.</p><p className="small-text" style={{marginTop:18}}>An included area missed? Let us know within 24 hours so we can make it right.</p></aside></div></div>{step>0&&quote&&!quote.review&&<div className="mobile-price"><span>This visit</span><a href="#price-summary"><strong>{money(quote.total)}</strong><ChevronDown size={17}/></a></div>}</div>;
}
