'use client';
import {useSearchParams} from 'next/navigation';
import {useEffect,useState} from 'react';
import {CheckCircle2,Clock3} from 'lucide-react';
import {CTA} from './ui';
import {money,serviceNames,type Service} from '@/lib/pricing';
import {slotDate,slotTime} from './booking-flow';
type Result={status?:string;error?:string;reference?:string;service?:Service;amount?:number;slot?:{starts_at:string;ends_at:string};emailStatus?:string};
export function Confirmation(){const params=useSearchParams();const id=params.get('session_id');const [result,setResult]=useState<Result>({status:'loading'});useEffect(()=>{let cancelled=false;let attempts=0;let timer:ReturnType<typeof setTimeout>;async function check(){try{const r=await fetch('/api/booking-status?session_id='+encodeURIComponent(id||''),{cache:'no-store'});const data=await r.json();if(cancelled)return;setResult(data);if((data.status==='pending'||!r.ok)&&attempts++<5)timer=setTimeout(check,3000);}catch{if(!cancelled)setResult({error:'We couldn’t check your payment. Please refresh in a moment. Do not pay again.'});}}check();return()=>{cancelled=true;clearTimeout(timer)}},[id]);return <section className="container content-section"><div className="success-panel">{result.status==='confirmed'?<><CheckCircle2 size={46} color="#297b7d"/><p className="eyebrow" style={{marginTop:22}}>One less thing on your list</p><h1 style={{fontSize:'4rem'}}>Your home is handled.</h1><p>Your cleaning is confirmed. Your reference is <strong>{result.reference}</strong>.</p><div className="panel" style={{maxWidth:520,margin:'28px auto',textAlign:'left'}}><h2>{serviceNames[result.service!]}</h2><p>{slotDate(result.slot!.starts_at)}<br/>Scheduled start: {slotTime(result.slot!.starts_at)} Eastern<br/>Estimated finish: {slotTime(result.slot!.ends_at)} Eastern</p><p><strong>Paid {money(result.amount!)}</strong></p><p className="small-text">{result.emailStatus==='sent'?'Your confirmation email has been sent.':'Your confirmation email is queued for delivery. Save your booking reference above.'}</p></div><p>Need to change something? Reply to your confirmation or contact us with your reference.</p><CTA href="/contact">Contact us</CTA></>:<><Clock3 size={40}/><h1 style={{fontSize:'3rem',marginTop:25}}>{result.status==='expired'?'Checkout has expired.':'Checking your payment.'}</h1><p>{result.error|| (result.status==='expired'?'No booking was confirmed from this checkout. Please choose a new appointment.':'Please keep this page open while we verify your payment. Do not submit another payment.')}</p><CTA href={result.status==='expired'?'/book':'/contact'}>{result.status==='expired'?'Get my instant price':'Contact us'}</CTA></>}</div></section>;}
