'use client';
import {useState} from 'react';
import {Check,ArrowRight} from 'lucide-react';
import Link from 'next/link';
import type {QuoteInput} from '@/lib/pricing';
export function ContactForm({type,quote,address='',stage='inquiry',compact=false,leadReady=true}:{type:'residential'|'commercial'|'contact';quote?:QuoteInput;address?:string;stage?:string;compact?:boolean;leadReady?:boolean}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [done,setDone]=useState(false);
 if(done)return <div className="success-panel" role="status"><Check size={32}/><h2>{type==='commercial'?'Your plan starts here.':'You’re on our list.'}</h2><p>We’ve received your details and will follow up about your {type==='commercial'?'property':'request'}. No appointment is confirmed and no payment has been taken.</p></div>;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const fd=new FormData(e.currentTarget);try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,quote,address:fd.get('address')||address,stage,contact:{name:fd.get('name'),email:fd.get('email'),phone:fd.get('phone')},company:fd.get('company')||'',businessType:fd.get('businessType')||'',squareFeet:fd.get('squareFeet')||'',frequency:fd.get('frequency')||'',preferredContact:fd.get('preferredContact')||'email',notes:fd.get('notes')||'',website:fd.get('website')||''})});const d=await r.json();if(!r.ok)throw new Error(d.error);setDone(true);}catch(e){setError(e instanceof Error?e.message:'We couldn’t send your request. Please try again.');}finally{setBusy(false)}}
 return <form onSubmit={submit} className={compact?'contact-form compact':'contact-form'} style={compact?{marginTop:25}:undefined}>{!leadReady&&<p className="notice">Online inquiries are being set up. Please check back soon.</p>}{type==='commercial'&&<label className="field"><span>Company / organization</span><input name="company" required maxLength={150} autoComplete="organization"/></label>}<label className="field"><span>Your name</span><input required name="name" minLength={2} maxLength={120} autoComplete="name"/></label><div className="field-row"><label className="field"><span>Email</span><input required name="email" type="email" autoComplete="email"/></label><label className="field"><span>Phone</span><input required name="phone" type="tel" minLength={10} maxLength={25} autoComplete="tel"/></label></div>{type==='commercial'&&<><label className="field"><span>Property address</span><input required name="address" autoComplete="street-address" maxLength={300}/></label><div className="field-row"><label className="field"><span>Approx. square feet</span><input required name="squareFeet" type="number" min={1} max={10000000}/></label><label className="field"><span>Property type</span><select name="businessType" required><option value="">Choose a type</option>{['Office','Retail','Professional business','Church','Common areas','Vacation rental portfolio','Small commercial property'].map(s=><option key={s}>{s}</option>)}</select></label></div><label className="field"><span>Desired frequency</span><select name="frequency"><option>Let’s discuss</option><option>One time</option><option>Daily</option><option>Several times a week</option><option>Weekly</option><option>Every two weeks</option><option>Every four weeks</option><option>Between guest stays</option></select></label></>}<label className="field"><span>Best way to reach you</span><select name="preferredContact"><option value="email">Email</option><option value="phone">Phone call</option><option value="text">Text message</option></select></label><label className="field"><span>{type==='contact'?'How can we help?':'Anything else we should know?'} <small>{type==='contact'?'':'Optional'}</small></span><textarea name="notes" maxLength={3000} required={type==='contact'}/></label><div className="honey" aria-hidden="true"><label>Website<input tabIndex={-1} name="website" autoComplete="off"/></label></div><p className="small-text" style={{marginBottom:18}}>By submitting, you’re asking us to contact you about this request. <Link href="/policies/privacy" className="row-link">Privacy Policy</Link>.</p>{error&&<p role="alert" className="error-message">{error}</p>}<button className="button full" disabled={busy||!leadReady}>{busy?'Sending…':type==='commercial'?'Get a commercial cleaning plan':type==='contact'?'Send my message':'Send my details'}<ArrowRight size={17}/></button></form>;
}
