'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
export function FeedbackForm(){
 const [token,setToken]=useState(''),[reference,setReference]=useState(''),[rating,setRating]=useState(0),[message,setMessage]=useState(''),[contactRequested,setContactRequested]=useState(false),[reviewUrl,setReviewUrl]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(true),[saved,setSaved]=useState(false);
 useEffect(()=>{const t=new URLSearchParams(window.location.hash.slice(1)).get('token')||'';setToken(t);if(!t){setError('Open the private feedback link in your follow-up email.');setBusy(false);return;}
 let active=true;fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'read',token:t})}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(active){window.history.replaceState(null,'',window.location.pathname+window.location.search);setReference(d.reference);setReviewUrl(d.reviewUrl);if(d.feedback){setRating(d.feedback.rating);setMessage(d.feedback.message);setContactRequested(d.feedback.contact_requested);}}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false};},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'submit',token,rating,message,contactRequested})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSaved(true);setReviewUrl(d.reviewUrl);}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}
 return <div className="container section" style={{maxWidth:720}}><p className="eyebrow">Your home, handled.</p><h1>How did we do?</h1><p style={{margin:'20px 0'}}>Tell us what you loved and what we could do better. Your feedback goes directly to our team.</p>{busy&&!reference&&<p role="status">Opening your feedback form…</p>}{reference&&!saved&&<form onSubmit={submit}><p className="small-text" style={{marginBottom:20}}>Your cleaning · {reference}</p><fieldset style={{border:0,padding:0,margin:'0 0 24px'}}><legend style={{marginBottom:12}}>How was your cleaning?</legend><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{[1,2,3,4,5].map(n=><label className="choice" key={n} style={{padding:12,minWidth:55,cursor:'pointer'}}><input required type="radio" name="rating" value={n} checked={rating===n} onChange={()=>setRating(n)} aria-label={`${n} out of 5`}/><span>{n}</span></label>)}</div><p className="small-text">1 — Needs improvement · 5 — Excellent</p></fieldset><label className="field"><span>Anything you’d like us to know?</span><textarea maxLength={4000} rows={5} value={message} onChange={e=>setMessage(e.target.value)}/></label><label className="check-field"><input type="checkbox" checked={contactRequested} onChange={e=>setContactRequested(e.target.checked)}/><span>Please contact me about my cleaning.</span></label><button disabled={busy||!rating} className="button" style={{marginTop:20}}>{busy?'Sending…':'Send feedback'}</button></form>}{saved&&<div className="notice" role="status"><h2>Thank you for telling us.</h2><p>Our team has received your feedback.{contactRequested?' You’ve also asked us to follow up with you.':''}</p></div>}{error&&<p className="error-message" role="alert">{error}</p>}{reviewUrl&&<div style={{marginTop:32}}><h2>Share an honest review.</h2><p style={{margin:'12px 0 18px'}}>Your experience can help another neighbor choose their homekeeping team.</p><a className="button outline" href={reviewUrl} target="_blank" rel="noopener noreferrer">Leave a public review</a></div>}<p className="small-text" style={{marginTop:28}}>Something included was missed? <Link href="/contact">Contact us</Link> within 24 hours and we’ll arrange a return to correct that area. Please leave entry codes and other private access details out of your feedback.</p></div>;
}
