'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {money,frequencyNames,serviceNames,type Frequency,type Service} from '@/lib/pricing';
import {slotDate,slotTime} from '@/lib/appointment-display';
export function SubscriptionManage(){
 const loaded=useRef(false);const [token,setToken]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function request(action:string,key=token){setBusy(true);setError('');try{const r=await fetch('/api/subscription',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:key,action})});const result=await r.json();if(!r.ok)throw new Error(result.error);if(result.url)window.location.assign(result.url);else setData(result);}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}
 useEffect(()=>{if(loaded.current)return;loaded.current=true;const value=new URLSearchParams(window.location.hash.slice(1)).get('token')||'';window.history.replaceState(null,'',window.location.pathname);if(!value){setError('Open the private manage-plan link in your latest cleaning email.');return}setToken(value);request('view',value)},[]);
 return <section className="container content-section" style={{maxWidth:850}}><p className="eyebrow">Your home, handled.</p><h1 style={{fontSize:'3rem'}}>Your cleaning routine.</h1>{error&&<p className="error-message" role="alert">{error}</p>}{busy&&!data&&<p>Loading your plan…</p>}{data&&<><div className="panel" style={{marginTop:25}}><h2>{serviceNames[data.plan.service as Service]}</h2><p>{frequencyNames[data.plan.frequency as Frequency]} · {money(data.plan.amount)} per visit, including your selected extras.</p><p>Your regular start: {new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'long'}).format(new Date(data.plan.anchorStart))}, {slotTime(data.plan.anchorStart)} Eastern.</p><p>Status: {data.plan.status==='trialing'?'First visit prepaid':data.plan.status.replaceAll('_',' ')}</p><p style={{margin:'18px 0'}}>Automatic renewal charges start the day before your second cleaning. Canceling stops future renewals and releases unpaid future visits. Prepaid appointments stay booked; contact us to cancel or reschedule those under the appointment policy.</p><div className="actions-inline"><button className="button" disabled={busy} onClick={()=>request('portal')}>Payment details & invoices</button>{!['canceled','incomplete_expired'].includes(data.plan.status)&&<button className="button outline" disabled={busy} onClick={()=>{if(window.confirm('Stop this subscription and future automatic charges? Your prepaid appointments will remain booked.'))request('cancel')}}>Cancel subscription</button>}</div></div><h2 style={{marginTop:35}}>Your next cleanings</h2>{data.visits.length?data.visits.map((visit:any)=><div className="notice" key={visit.reference} style={{marginTop:15}}><strong>{slotDate(visit.starts_at)} · {slotTime(visit.starts_at)} Eastern</strong><p>{visit.payment_status==='paid'?'Paid':visit.payment_status==='failed'?'Payment needs attention':'Reserved · automatic payment scheduled'} · {visit.reference}</p></div>):<p>No upcoming appointments.</p>}</>}<p style={{marginTop:25}}>Need help or a different routine? <Link className="text-link" href="/contact">Contact us</Link>.</p></section>;
}
