import Link from 'next/link';
import {notFound} from 'next/navigation';
import {PageIntro} from '@/components/ui';
const policies:Record<string,{title:string;intro:string;sections:{title:string;text:string[]}[]}>={
 terms:{title:'Terms of service',intro:'Clear expectations for your Carolina Homekeeping appointment.',sections:[
 {title:'Who we are',text:['Carolina Homekeeping Co. is operated by Send A Scout LLC d/b/a Carolina Homekeeping Co., serving selected addresses in the New Bern, North Carolina area.']},
 {title:'Booking and pricing',text:['Provide accurate home details, conditions, access instructions and contact information. Your complete appointment price is shown before payment. A booking is confirmed after payment is verified and a booking reference is issued. Available windows describe arrival, not the total time spent cleaning.','Online prices apply to the listed scope and ordinary conditions. Homes of 3,500 square feet or more and unusual or excessive conditions require review. If information or conditions change the scope, we will discuss the change and obtain agreement before additional work or charges.']},
 {title:'Payment and recurring service',text:['Payments are processed by Stripe. We do not store full card numbers. Selecting a recurring frequency applies the displayed savings to the booked cleaning and records your requested routine. Only the appointment shown at checkout is paid for. Future dates and payments are coordinated separately; this is not an automatic subscription.','Discounts apply to base cleaning and configured room adjustments, not optional add-ons. Any applicable tax is displayed in the total before payment.']},
 {title:'Preparing your home',text:['Provide safe access, running water, electricity and a reasonably safe working temperature. Secure pets, valuables, fragile items and sensitive documents. Tell us about delicate surfaces, allergies, product requirements and areas we should not enter. Clear floors and surfaces sufficiently for cleaning.','Move cleaning requires a home emptied of furniture and belongings. Empty appliances and cabinets before interior add-ons. For laundry, provide a working washer and dryer, suitable products and care instructions. We may decline items needing specialist care or cycles that cannot be completed during the appointment.']},
 {title:'Scope and limitations',text:['Our service is cleaning and homekeeping, not restoration or remediation. We exclude biohazards, mold, pests, animal waste, hoarding, construction debris, unsafe areas, high ladder work, heavy furniture moving and appliance disassembly. Permanent stains, wear and pre-existing damage may remain after cleaning.','We may stop work if access or conditions are unsafe, and will contact you to discuss next steps and any appropriate adjustment for unperformed services. We do not add unapproved work or fees.']},
 {title:'Changes, concerns and policies',text:['The Cancellation & Rescheduling and Service & Satisfaction policies form part of these terms. If you believe an item was damaged or a service was missed, contact us promptly with the booking reference and relevant details so we can investigate.','These terms do not remove rights or remedies that applicable law gives you. Changes to these terms apply to future bookings; the policy version accepted for a booking is retained with that booking.']},
 ]},
 cancellation:{title:'Cancellation & rescheduling',intro:'Plans change. Here’s how we handle changes to your appointment.',sections:[
 {title:'More than 48 hours before arrival',text:['Cancel or reschedule without a cancellation fee. A cancelled prepaid appointment receives a refund to the original payment method. Rescheduling is subject to available capacity.']},
 {title:'From 24 through 48 hours before arrival',text:['A cancellation fee of 25% of the booked service amount applies. Alternatively, you may request a reschedule credit for the amount already paid, subject to available appointment capacity.']},
 {title:'Less than 24 hours before arrival',text:['A cancellation charge of 50% of the booked service amount applies. Any remaining prepaid amount is refunded to the original payment method. We will discuss the handling of a last-minute reschedule with you before making changes.']},
 {title:'If we cannot access your property',text:['If we cannot gain safe access during the booked arrival window after reasonable attempts to reach you using your booking contact details, a charge of up to 100% of the booked service amount may apply. The amount is reviewed based on the circumstances and work capacity reserved.']},
 {title:'How to request a change',text:['Reply to your confirmation email or send a message through our Contact page. Include your booking reference, appointment date and requested change. The time we receive your request is used to calculate notice, based on the beginning of the arrival window in Eastern Time.','Cancellation charges are based on the booked service amount before applicable tax; any tax adjustments are reflected in the refund. Refund processing time depends on Stripe and your bank.']},
 {title:'Changes on our side',text:['If we need to cancel, you may choose an available replacement appointment or a refund for unperformed service. If severe weather or unsafe conditions affect a visit, we will contact you to discuss rescheduling or the appropriate resolution.']},
 ]},
 service:{title:'Service & satisfaction policy',intro:'Thoughtful care, a clear scope and a chance to make an included area right.',sections:[
 {title:'Our service promise',text:['If an area included in your booked cleaning was missed, contact us within 24 hours of completion. Tell us what was missed and provide your booking reference. We will arrange a return visit to correct that area at no additional charge, at a mutually workable time.','This return visit covers the missed portion of the original service. It does not include new messes, additional services, permanent stains or damage, or work outside the booked scope.']},
 {title:'What is included',text:['Standard cleaning focuses on normally maintained kitchens, bathrooms, mirrors, accessible surfaces and floors, normal household trash, appropriate bed making and general straightening. Deep cleaning adds the detail listed on our Services page. Move cleaning adds accessible empty cabinets, drawers and closets in an empty home.','Selected add-ons are listed separately in your booking summary. All cleaning is limited to areas we can safely access.']},
 {title:'Conditions requiring review',text:['Excessive buildup, heavy clutter, pests, biohazards, mold, construction debris or unsafe conditions may prevent us from performing the planned service. We will communicate with you about the scope and available options before any additional charge. Cleaning cannot repair worn finishes or guarantee removal of permanent stains.']},
 {title:'Damage or other concerns',text:['Please report suspected damage promptly and preserve relevant information so we can investigate fairly. We will review the facts and communicate next steps. This policy does not limit rights available under applicable law.']},
 ]},
 privacy:{title:'Privacy policy',intro:'Your home is personal. We keep our use of your information focused on providing and supporting your service.',sections:[
 {title:'Information we collect',text:['We collect information you provide, such as your name, email, phone number, service address, home details, chosen cleaning, appointment preferences, access instructions and service messages. We also retain booking, payment reference, policy acceptance and service history records.','Our hosting and service providers may process technical information such as IP addresses and request logs to operate and protect the website. Essential cookies support secure administration and allow us to associate an incomplete booking with its checkout.']},
 {title:'Incomplete bookings and inquiries',text:['When you provide your contact details and continue toward payment or submit an inquiry, we save the information as a lead even if payment is not completed. We may contact you about that requested cleaning or inquiry. Submitting a request does not enroll you in an unrelated marketing campaign.']},
 {title:'How information is used and shared',text:['We use information to price and arrange services, process payments, send confirmations, communicate about your request, provide relevant instructions to assigned personnel, maintain records and respond to concerns. Information is shared with providers only as needed for these functions, such as hosting, database, payment and email services.','Stripe processes payment details under its own privacy terms. We retain payment references and transaction status, but do not store full payment-card numbers. We do not sell your personal information.']},
 {title:'Access details and home photos',text:['Home access information is restricted to authorized staff who need it. Avoid placing sensitive information in general notes unless needed for your service.','Operational photo collection is not enabled in this initial booking system. If introduced, we will request explicit consent before taking before-and-after photos inside your home. Photos will use private storage and restricted access. We will not publish home photos for marketing without separate permission.']},
 {title:'Retention and your choices',text:['We retain information as needed to provide services, follow up on inquiries, maintain appropriate business records, handle disputes and meet applicable obligations. Access instructions should be removed when no longer needed.','Contact us to ask about your information, request corrections or deletion, or stop follow-up about an inquiry. Some records may need to be retained for legal, accounting or transaction purposes. We use reasonable safeguards, but no system can promise absolute security.']},
 {title:'Contact and updates',text:['Use our Contact page or reply to your confirmation email for privacy requests. This policy may be updated as our services develop. The current version is published here.']},
 ]},
};
export function generateStaticParams(){return Object.keys(policies).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){return {title:policies[(await params).slug]?.title||'Policy'};}
export default async function Policy({params}:{params:Promise<{slug:string}>}){const policy=policies[(await params).slug];if(!policy)notFound();return <><PageIntro label="The helpful details" title={policy.title}>{policy.intro}</PageIntro><article className="container policy-content"><p className="small-text">Effective September 19, 2026 · Policy version 2026-09-19</p>{policy.sections.map(s=><section key={s.title}><h2>{s.title}</h2>{s.text.map(t=><p key={t}>{t}</p>)}</section>)}<p>Questions? <Link href="/contact">Contact Carolina Homekeeping</Link>.</p><p className="small-text"><Link href="/policies/terms">Terms</Link> · <Link href="/policies/privacy">Privacy</Link> · <Link href="/policies/cancellation">Cancellation</Link> · <Link href="/policies/service">Service & Satisfaction</Link></p></article></>;}
